// flow-typed signature: d97468b107b012ecf7b6eee2b93b71fa
// flow-typed version: <<STUB>>/class-autobind_v^0.1.4/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'class-autobind'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'class-autobind' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'class-autobind/lib/autobind' {
  declare module.exports: any;
}

// Filename aliases
declare module 'class-autobind/lib/autobind.js' {
  declare module.exports: $Exports<'class-autobind/lib/autobind'>;
}
